# Ansible YAML pipeline

trigger:
- main

pool:
  name: Ubuntu

steps:
- task: CopyFiles@2
  displayName: 'Copy Playbooks to Artifacts'
  inputs:
    SourceFolder: playbooks
    TargetFolder: '$(build.artifactstagingdirectory)/Playbooks'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'


- task: Ansible@0
  displayName: 'Run playbook'
  inputs:
    playbookRootRemoteMachine: '$(System.DefaultWorkingDirectory)/playbooks'
    playbookPathLinkedArtifactOnRemoteMachine: playbook.yml
    playbookPathOnAgentMachine: '$(System.DefaultWorkingDirectory)/playbooks/playbook.yml'
    inventoriesRemoteMachine: hostList
    inventoryHostListRemoteMachine: 192.168.100.202
    failOnStdErr: false
